<?php
namespace inflector\inflection;

use inflector\Inflector;

return function($locale) {
    Inflector::singular('/([^s])s$/i', '\1', 'auto');
    Inflector::plural('/([^s])$/i', '\1s', 'auto');

    Inflector::singular('/(x|z|s|ss|ch|sh)es$/i', '\1', 'auto');
    Inflector::plural('/(x|z|ss|ch|sh)$/i', '\1es', 'auto');

    Inflector::singular('/ies$/i', 'y', 'auto');
    Inflector::plural('/([^aeiouy]|qu)y$/i', '\1ies', 'auto');

    Inflector::plural('/(meta|data)$/i', '\1', 'auto');

    Inflector::irregular('child', 'children', 'auto');
    Inflector::irregular('equipment', 'equipment', 'auto');
    Inflector::irregular('information', 'information', 'auto');
    Inflector::irregular('man', 'men', 'auto');
    Inflector::irregular('news', 'news', 'auto');
    Inflector::irregular('person', 'people', 'auto');
    Inflector::irregular('woman', 'women', 'auto');

    /**
     * Warning, using an "exhastive" list of rules will slow
     * down all singularizations/pluralizations generations.
     * So it may be preferable to only add the ones you are actually needed.
     *
     * Anyhow bellow a list english exceptions which are not covered
     * by the above rules.
     */
    // Inflector::irregular('advice', 'advice', 'auto');
    // Inflector::irregular('aircraft', 'aircraft', 'auto');
    // Inflector::irregular('alias', 'aliases', 'auto');
    // Inflector::irregular('alga', 'algae', 'auto');
    // Inflector::irregular('alumna', 'alumnae', 'auto');
    // Inflector::irregular('alumnus', 'alumni', 'auto');
    // Inflector::irregular('analysis', 'analyses', 'auto');
    // Inflector::irregular('antenna', 'antennae', 'auto');
    // Inflector::irregular('automaton', 'automata', 'auto');
    // Inflector::irregular('axis', 'axes', 'auto');
    // Inflector::irregular('bacillus', 'bacilli', 'auto');
    // Inflector::irregular('bacterium', 'bacteria', 'auto');
    // Inflector::irregular('barracks', 'barracks', 'auto');
    // Inflector::irregular('basis', 'bases', 'auto');
    // Inflector::irregular('bellows', 'bellows', 'auto');
    // Inflector::irregular('buffalo', 'buffaloes', 'auto');
    // Inflector::irregular('bus', 'buses', 'auto');
    // Inflector::irregular('bison', 'bison', 'auto');
    // Inflector::irregular('cactus', 'cacti', 'auto');
    // Inflector::irregular('cafe', 'cafes', 'auto');
    // Inflector::irregular('calf', 'calves', 'auto');
    // Inflector::irregular('cargo', 'cargoes', 'auto');
    // Inflector::irregular('cattle', 'cattle', 'auto');
    // Inflector::irregular('child', 'children', 'auto');
    // Inflector::irregular('congratulations', 'congratulations', 'auto');
    // Inflector::irregular('corn', 'corn', 'auto');
    // Inflector::irregular('crisis', 'crises', 'auto');
    // Inflector::irregular('criteria', 'criterion', 'auto');
    // Inflector::irregular('curriculum', 'curricula', 'auto');
    // Inflector::irregular('datum', 'data', 'auto');
    // Inflector::irregular('deer', 'deer', 'auto');
    // Inflector::irregular('die', 'dice', 'auto');
    // Inflector::irregular('dregs', 'dregs', 'auto');
    // Inflector::irregular('duck', 'duck', 'auto');
    // Inflector::irregular('echo', 'echos', 'auto');
    // Inflector::irregular('elf', 'elves', 'auto');
    // Inflector::irregular('ellipsis', 'ellipses', 'auto');
    // Inflector::irregular('embargo', 'embargoes', 'auto');
    // Inflector::irregular('equipment', 'equipment', 'auto');
    // Inflector::irregular('erratum', 'errata', 'auto');
    // Inflector::irregular('evidence', 'evidence', 'auto');
    // Inflector::irregular('eyeglasses', 'eyeglasses', 'auto');
    // Inflector::irregular('fish', 'fish', 'auto');
    // Inflector::irregular('focus', 'foci', 'auto');
    // Inflector::irregular('foot', 'feet', 'auto');
    // Inflector::irregular('fungus', 'fungi', 'auto');
    // Inflector::irregular('gallows', 'gallows', 'auto');
    // Inflector::irregular('genus', 'genera', 'auto');
    // Inflector::irregular('goose', 'geese', 'auto');
    // Inflector::irregular('gold', 'gold', 'auto');
    // Inflector::irregular('grotto', 'grottoes', 'auto');
    // Inflector::irregular('gymnasium', 'gymnasia', 'auto');
    // Inflector::irregular('half', 'halves', 'auto');
    // Inflector::irregular('headquarters', 'headquarters', 'auto');
    // Inflector::irregular('hoof', 'hooves', 'auto');
    // Inflector::irregular('hypothesis', 'hypotheses', 'auto');
    // Inflector::irregular('information', 'information', 'auto');
    // Inflector::irregular('graffito', 'graffiti', 'auto');
    // Inflector::irregular('half', 'halves', 'auto');
    // Inflector::irregular('hero', 'heroes', 'auto');
    // Inflector::irregular('jewelry', 'jewelry', 'auto');
    // Inflector::irregular('kin', 'kin', 'auto');
    // Inflector::irregular('knife', 'knives', 'auto');
    // Inflector::irregular('larva', 'larvae', 'auto');
    // Inflector::irregular('leaf', 'leaves', 'auto');
    // Inflector::irregular('legislation', 'legislation', 'auto');
    // Inflector::irregular('life', 'lives', 'auto');
    // Inflector::irregular('loaf', 'loaves', 'auto');
    // Inflector::irregular('locus', 'loci', 'auto');
    // Inflector::irregular('louse', 'lice', 'auto');
    // Inflector::irregular('luck', 'luck', 'auto');
    // Inflector::irregular('luggage', 'luggage', 'auto');
    // Inflector::irregular('man', 'men', 'auto');
    // Inflector::irregular('mathematics', 'mathematics', 'auto');
    // Inflector::irregular('matrix', 'matrices', 'auto');
    // Inflector::irregular('means', 'means', 'auto');
    // Inflector::irregular('measles', 'measles', 'auto');
    // Inflector::irregular('medium', 'media', 'auto');
    // Inflector::irregular('memorandum', 'memoranda', 'auto');
    // Inflector::irregular('money', 'monies', 'auto');
    // Inflector::irregular('moose', 'moose', 'auto');
    // Inflector::irregular('mosquito', 'mosquitoes', 'auto');
    // Inflector::irregular('motto', 'mottoes', 'auto');
    // Inflector::irregular('mouse', 'mice', 'auto');
    // Inflector::irregular('mumps', 'mumps', 'auto');
    // Inflector::irregular('music', 'music', 'auto');
    // Inflector::irregular('mythos', 'mythoi', 'auto');
    // Inflector::irregular('nebula', 'nebulae', 'auto');
    // Inflector::irregular('neurosis', 'neuroses', 'auto');
    // Inflector::irregular('news', 'news', 'auto');
    // Inflector::irregular('nucleus', 'nuclei', 'auto');
    // Inflector::irregular('numen', 'numina', 'auto');
    // Inflector::irregular('oasis', 'oases', 'auto');
    // Inflector::irregular('oats', 'oats', 'auto');
    // Inflector::irregular('octopus', 'octopuses', 'auto');
    // Inflector::irregular('offspring', 'offspring', 'auto');
    // Inflector::irregular('ovum', 'ova', 'auto');
    // Inflector::irregular('ox', 'oxen', 'auto');
    // Inflector::irregular('pajamas', 'pajamas', 'auto');
    // Inflector::irregular('pants', 'pants', 'auto');
    // Inflector::irregular('paralysis', 'paralyses', 'auto');
    // Inflector::irregular('parenthesis', 'parentheses', 'auto');
    // Inflector::irregular('person', 'people', 'auto');
    // Inflector::irregular('phenomenon', 'phenomena', 'auto');
    // Inflector::irregular('pike', 'pike', 'auto');
    // Inflector::irregular('plankton', 'plankton', 'auto');
    // Inflector::irregular('pliers', 'pliers', 'auto');
    // Inflector::irregular('polyhedron', 'polyhedra', 'auto');
    // Inflector::irregular('potato', 'potatoes', 'auto');
    // Inflector::irregular('quiz', 'quizzes', 'auto');
    // Inflector::irregular('radius', 'radii', 'auto');
    // Inflector::irregular('roof', 'roofs', 'auto');
    // Inflector::irregular('salmon', 'salmon', 'auto');
    // Inflector::irregular('scarf', 'scarves', 'auto');
    // Inflector::irregular('scissors', 'scissors', 'auto');
    // Inflector::irregular('self', 'selves', 'auto');
    // Inflector::irregular('series', 'series', 'auto');
    // Inflector::irregular('shears', 'shears', 'auto');
    // Inflector::irregular('sheep', 'sheep', 'auto');
    // Inflector::irregular('shelf', 'shelves', 'auto');
    // Inflector::irregular('shorts', 'shorts', 'auto');
    // Inflector::irregular('silver', 'silver', 'auto');
    // Inflector::irregular('species', 'species', 'auto');
    // Inflector::irregular('squid', 'squid', 'auto');
    // Inflector::irregular('stimulus', 'stimuli', 'auto');
    // Inflector::irregular('stratum', 'strata', 'auto');
    // Inflector::irregular('swine', 'swine', 'auto');
    // Inflector::irregular('syllabus', 'syllabi', 'auto');
    // Inflector::irregular('synopsis', 'synopses', 'auto');
    // Inflector::irregular('synthesis', 'syntheses', 'auto');
    // Inflector::irregular('tax', 'taxes', 'auto');
    // Inflector::irregular('terminus', 'termini', 'auto');
    // Inflector::irregular('thesis', 'theses', 'auto');
    // Inflector::irregular('thief', 'thieves', 'auto');
    // Inflector::irregular('tomato', 'tomatoes', 'auto');
    // Inflector::irregular('tongs', 'tongs', 'auto');
    // Inflector::irregular('tooth', 'teeth', 'auto');
    // Inflector::irregular('torpedo', 'torpedoes', 'auto');
    // Inflector::irregular('torus', 'tori', 'auto');
    // Inflector::irregular('trousers', 'trousers', 'auto');
    // Inflector::irregular('trout', 'trout', 'auto');
    // Inflector::irregular('tweezers', 'tweezers', 'auto');
    // Inflector::irregular('vertebra', 'vertebrae', 'auto');
    // Inflector::irregular('vertex', 'vertices', 'auto');
    // Inflector::irregular('vespers', 'vespers', 'auto');
    // Inflector::irregular('veto', 'vetoes', 'auto');
    // Inflector::irregular('volcano', 'volcanoes', 'auto');
    // Inflector::irregular('vortex', 'vortices', 'auto');
    // Inflector::irregular('vita', 'vitae', 'auto');
    // Inflector::irregular('virus', 'viri', 'auto');
    // Inflector::irregular('wheat', 'wheat', 'auto');
    // Inflector::irregular('wife', 'wives', 'auto');
    // Inflector::irregular('wolf', 'wolves', 'auto');
    // Inflector::irregular('woman', 'women', 'auto');
    // Inflector::irregular('zero', 'zeros', 'auto');
};
